### ISSUE TITLE
Падает бот при вводе артикула

### ISSUE THREAD

**Issue by spabaex** [kostyamorales/wildberries_helper_bot#1]
Запустил всё как в гайде. Стоит Убунту 20, питон 3.9. Бот реагирует на команды, но если ввести артикул в любом меню, бот сразу падает :C  Что я делаю не так?
![image](https://user-images.githubusercontent.com/68686778/123961171-c0653480-d9b8-11eb-9472-740394718146.png)

**Comment by kostyamorales** [comment]
Привет! Traceback показывает, что код не может найти validate_article. Это функция кот сюда импортируется из файла validators.py. Вы весь репозиторий скопировали? Опишите процесс установки.

Sent with a Spark
30 июня 2021 г., 15:37 +0300, spabaex ***@***.***>, писал:

**Comment by spabaex** [comment]
> Привет! Traceback показывает, что код не может найти validate_article. Это функция кот сюда импортируется из файла validators.py. Вы весь репозиторий скопировали? Опишите процесс установки. Sent with a Spark 30 июня 2021 г., 15:37 


Привет, репозиторий конечно весь загрузил. Как устанавливал: создал папку, перенёс туда репозиторий, установил туда виртуальное окружение, создал ."env" файлик, прописал ключи. Запускаю через "sudo python3 tg_bot.py". Пробовал и с разными правами и через screen - не помогло :C

**Comment by kostyamorales** [comment]
Напишите мне пожалуйста в телеграм @kostya_morales

**Comment by kostyamorales** [comment]
> > Привет! Traceback показывает, что код не может найти validate_article. Это функция кот сюда импортируется из файла validators.py. Вы весь репозиторий скопировали? Опишите процесс установки. Sent with a Spark 30 июня 2021 г., 15:37
> 
> Привет, репозиторий конечно весь загрузил. Как устанавливал: создал папку, перенёс туда репозиторий, установил туда виртуальное окружение, создал ."env" файлик, прописал ключи. Запускаю через "sudo python3 tg_bot.py". Пробовал и с разными правами и через screen - не помогло :C

Напишите мне пожалуйста в телеграм @kostya_morales если не разобрались. Если разобрались тоже напишите пожалуйста.

**Comment by spabaex** [comment]
Заработало, после установки на чистую систему. (Запускать нужно обязательно из под виртуального окружения.)
